root: true
extends: airbnb
parser: babel-eslint
env:
  mocha: true
plugins:
  - babel
rules:
  max-len: 0
  no-console: 0
  generator-star-spacing: 0
  arrow-parens: 0
  babel/arrow-parens: [2, 'as-needed']
  import/no-extraneous-dependencies: [2, {}]
