module.exports = {
  states: [{ state: 'US', stateName: 'United States', raceId: 5491 },
{ state: 'AL', stateName: 'Alabama', raceId: null },
{ state: 'AK', stateName: 'Alaska', raceId: 5884 },
{ state: 'AZ', stateName: 'Arizona', raceId: 5832 },
{ state: 'AR', stateName: 'Arkansas', raceId: 5899 },
{ state: 'CA', stateName: 'California', raceId: 5849 },
{ state: 'CO', stateName: 'Colorado', raceId: 5751 },
{ state: 'CT', stateName: 'Connecticut', raceId: 5720 },
{ state: 'DC', stateName: 'District of Columbia', raceId: null },
{ state: 'DE', stateName: 'Delaware', raceId: null },
{ state: 'FL', stateName: 'Florida', raceId: 5635 },
{ state: 'GA', stateName: 'Georgia', raceId: 5741 },
{ state: 'HI', stateName: 'Hawaii', raceId: null },
{ state: 'ID', stateName: 'Idaho', raceId: null },
{ state: 'IL', stateName: 'Illinois', raceId: 5583 },
{ state: 'IN', stateName: 'Indiana', raceId: 5878 },
{ state: 'IA', stateName: 'Iowa', raceId: 5597 },
{ state: 'KS', stateName: 'Kansas', raceId: 5904 },
{ state: 'KY', stateName: 'Kentucky', raceId: 5523 },
{ state: 'LA', stateName: 'Louisiana', raceId: 5696 },
{ state: 'ME', stateName: 'Maine', raceId: 5896 },
{ state: 'MECD', stateName: 'Maine', raceId: 5897 },
{ state: 'MD', stateName: 'Maryland', raceId: 5859 },
{ state: 'MA', stateName: 'Massachusetts', raceId: 5863 },
{ state: 'MI', stateName: 'Michigan', raceId: 5533 },
{ state: 'MN', stateName: 'Minnesota', raceId: 5591 },
{ state: 'MS', stateName: 'Mississipi', raceId: 5857 },
{ state: 'MO', stateName: 'Missouri', raceId: 5609 },
{ state: 'MT', stateName: 'Montana', raceId: null },
{ state: 'NE', stateName: 'Nebraska', raceId: null },
{ state: 'NECD', stateName: 'Nebraska', raceId: null },
{ state: 'NECD2', stateName: 'Nebraska', raceId: null },
{ state: 'NV', stateName: 'Nevada', raceId: 5891 },
{ state: 'NH', stateName: 'New Hampshire', raceId: 5596 },
{ state: 'NJ', stateName: 'New Jersey', raceId: 5872 },
{ state: 'NM', stateName: 'New Mexico', raceId: 5894 },
{ state: 'NY', stateName: 'New York', raceId: 5792 },
{ state: 'NC', stateName: 'North Carolina', raceId: 5538 },
{ state: 'ND', stateName: 'North Dakota', raceId: null },
{ state: 'OH', stateName: 'Ohio', raceId: 5634 },
{ state: 'OK', stateName: 'Oklahoma', raceId: null },
{ state: 'OR', stateName: 'Oregon', raceId: 5892 },
{ state: 'PA', stateName: 'Pennsylvania', raceId: 5633 },
{ state: 'RI', stateName: 'Rhode Island', raceId: null },
{ state: 'SC', stateName: 'South Carolina', raceId: 5748 },
{ state: 'SD', stateName: 'South Dakota', raceId: null },
{ state: 'TN', stateName: 'Tennessee', raceId: 5911 },
{ state: 'TX', stateName: 'Texas', raceId: 5694 },
{ state: 'UT', stateName: 'Utah', raceId: 5834 },
{ state: 'VT', stateName: 'Vermont', raceId: null },
{ state: 'VA', stateName: 'Virginia', raceId: 5542 },
{ state: 'WA', stateName: 'Washington', raceId: null },
{ state: 'WV', stateName: 'West Virginia', raceId: 5885 },
{ state: 'WI', stateName: 'Wisconsin', raceId: 5659 },
{ state: 'WY', stateName: 'Wyoming', raceId: null },
]};
